// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQNf_lZmp5_AUlYDiezdE1ShalwgZvES4',
    appId: '1:152116822938:web:e37496d5579c74c4ccb023',
    messagingSenderId: '152116822938',
    projectId: 'hostelmess-ac019',
    authDomain: 'hostelmess-ac019.firebaseapp.com',
    storageBucket: 'hostelmess-ac019.firebasestorage.app',
    measurementId: 'G-M2N3D34FSR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRgpG01IGUpyeixfGyOMHjiqAYNpiltxQ',
    appId: '1:152116822938:android:17d2bd8d216ac4cdccb023',
    messagingSenderId: '152116822938',
    projectId: 'hostelmess-ac019',
    storageBucket: 'hostelmess-ac019.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9Srp0csWgUCKLOmecWKJra_6vyeER09U',
    appId: '1:152116822938:ios:7a8d18b7d124c308ccb023',
    messagingSenderId: '152116822938',
    projectId: 'hostelmess-ac019',
    storageBucket: 'hostelmess-ac019.firebasestorage.app',
    iosBundleId: 'com.example.hostelMess',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9Srp0csWgUCKLOmecWKJra_6vyeER09U',
    appId: '1:152116822938:ios:7a8d18b7d124c308ccb023',
    messagingSenderId: '152116822938',
    projectId: 'hostelmess-ac019',
    storageBucket: 'hostelmess-ac019.firebasestorage.app',
    iosBundleId: 'com.example.hostelMess',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQNf_lZmp5_AUlYDiezdE1ShalwgZvES4',
    appId: '1:152116822938:web:6904574dda5e5fbeccb023',
    messagingSenderId: '152116822938',
    projectId: 'hostelmess-ac019',
    authDomain: 'hostelmess-ac019.firebaseapp.com',
    storageBucket: 'hostelmess-ac019.firebasestorage.app',
    measurementId: 'G-DMQBMTG96J',
  );
}
